use_frameworks!

platform :ios, '8.0'

target 'QzToolKit_Example' do
  pod 'QzToolKit', :path => '../'

  target 'QzToolKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
